/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.5.0
 *
 * Project: 'Bat_man+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f7xx.h"

/* Keil::CMSIS Driver:CAN@1.15.0 */
#define RTE_Drivers_CAN1                /* Driver CAN1 */
        #define RTE_Drivers_CAN2                /* Driver CAN2 */
        #define RTE_Drivers_CAN3                /* Driver CAN3 */
/* Keil::CMSIS Driver:SPI@1.15.0 */
#define RTE_Drivers_SPI1                /* Driver SPI1 */
        #define RTE_Drivers_SPI2                /* Driver SPI2 */
        #define RTE_Drivers_SPI3                /* Driver SPI3 */
        #define RTE_Drivers_SPI4                /* Driver SPI4 */
        #define RTE_Drivers_SPI5                /* Driver SPI5 */
        #define RTE_Drivers_SPI6                /* Driver SPI6 */
/* Keil::CMSIS Driver:USART@1.21.0 */
#define RTE_Drivers_USART1              /* Driver USART1 */
        #define RTE_Drivers_USART2              /* Driver USART2 */
        #define RTE_Drivers_USART3              /* Driver USART3 */
        #define RTE_Drivers_USART4              /* Driver USART4 */
        #define RTE_Drivers_USART5              /* Driver USART5 */
        #define RTE_Drivers_USART6              /* Driver USART6 */
        #define RTE_Drivers_USART7              /* Driver USART7 */
        #define RTE_Drivers_USART8              /* Driver USART8 */
/* Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:CAN@1.3.0 */
#define RTE_DEVICE_HAL_CAN
/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.3.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.3.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:ETH@1.3.0 */
#define RTE_DEVICE_HAL_ETH
/* Keil::Device:STM32Cube HAL:GPIO@1.3.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.3.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.3.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:SPI@1.3.0 */
#define RTE_DEVICE_HAL_SPI
/* Keil::Device:STM32Cube HAL:UART@1.3.0 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:STM32Cube HAL:USART@1.3.0 */
#define RTE_DEVICE_HAL_USART
/* Keil::Device:STM32Cube LL:Common@1.3.0 */
#define RTE_DEVICE_LL_COMMON
/* Keil::Device:STM32Cube LL:PWR@1.3.0 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device:STM32Cube LL:RCC@1.3.0 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device:STM32Cube LL:UTILS@1.3.0 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device:Startup@1.2.5 */
#define RTE_DEVICE_STARTUP_STM32F7XX    /* Device Startup for STM32F7 */


#endif /* RTE_COMPONENTS_H */
