/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.5.0
 *
 * Project: 'BAT-MAN_CMSIS.Debug+STM32F767ZITx' 
 * Target:  'Debug+STM32F767ZITx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define USE_HAL_DRIVER
/* Keil::Device:STM32Cube LL:Common@1.3.0 */
#define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
