/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'BAT-MAN_CMSIS.Debug+STM32F767ZITx' 
 * Target:  'Debug+STM32F767ZITx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f7xx.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
/* Keil::Device:Startup@1.2.5 */
#define RTE_DEVICE_STARTUP_STM32F7XX    /* Device Startup for STM32F7 */


#endif /* RTE_COMPONENTS_H */
