/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.5.0
 *
 * Project: 'BAT-MAN_CMSIS.Debug+STM32F767ZITx' 
 * Target:  'Debug+STM32F767ZITx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f7xx.h"

/* Keil::CMSIS Driver:USB Device:Full-speed@1.13.0 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
/* Keil::CMSIS Driver:USB Device:High-speed@1.19.0 */
#define RTE_Drivers_USBD1               /* Driver USBD1 */
/* Keil::Device:STM32Cube Framework:Classic@1.3.0 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.3.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.3.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.3.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.3.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.3.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube LL:Common@1.3.0 */
#define RTE_DEVICE_LL_COMMON
/* Keil::Device:STM32Cube LL:PWR@1.3.0 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device:STM32Cube LL:RCC@1.3.0 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device:STM32Cube LL:UTILS@1.3.0 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device:Startup@1.2.5 */
#define RTE_DEVICE_STARTUP_STM32F7XX    /* Device Startup for STM32F7 */


#endif /* RTE_COMPONENTS_H */
